# Defines CI/CD workflow: install deps, run tests, build/push images, migrate DB, deploy to Cloud Run, run smoke tests.
steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install dependencies'
    args: ['ci']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Generate Prisma client'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_DEPLOY_TARGET}" == "frontend" ]]; then
          echo 'Skipping Prisma client generation for frontend-only deployment';
          exit 0;
        fi
        npm run prisma:generate --workspace=backend

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Run backend tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_DEPLOY_TARGET}" == "frontend" ]]; then
          echo 'Skipping backend tests for frontend-only deployment';
          exit 0;
        fi
        npm run test --workspace=backend -- --runInBand

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build frontend (SSG check)'
    entrypoint: 'bash'
    env:
      - 'DEPLOY_TARGET=${_DEPLOY_TARGET}'
    args:
      - '-c'
      - |
        target="${DEPLOY_TARGET:-all}"
        echo "[Build frontend] target: ${target}"
        echo "[Build frontend] Deploy target: ${target}"
        if [[ "${target}" != "frontend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping frontend build for deploy target '${target}'";
          exit 0;
        fi
        NEXT_PUBLIC_API_URL="${_NEXT_PUBLIC_API_URL}" ./ci/check_frontend_build.sh

  - name: 'mcr.microsoft.com/playwright:v1.56.1-jammy'
    id: 'Run frontend smoke tests'
    entrypoint: 'bash'
    env:
      - 'DEPLOY_TARGET=${_DEPLOY_TARGET}'
    args:
      - '-c'
      - |
        target="${DEPLOY_TARGET:-all}"
        echo "DEPLOY_TARGET=${target}"
        if [[ "${target}" == "backend" ]]; then
          echo 'DEPLOY_TARGET=backend -> skipping frontend smoke tests';
          exit 0;
        fi
        if [[ "${target}" != "frontend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping frontend smoke tests for deploy target '${target}'";
          exit 0;
        fi

        set -euo pipefail
        cd frontend

        export NEXT_PUBLIC_BASE_URL="${_FRONTEND_BASE_URL:-https://hugs-frontend-prod-<DEINE-ID>.a.run.app}"
        export PW_BASE_URL="$${NEXT_PUBLIC_BASE_URL}"
        export NEXT_PUBLIC_API_URL="${_NEXT_PUBLIC_API_URL}"

        npm ci
        npm run test:e2e:ci

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build backend image'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        target="${_DEPLOY_TARGET:-all}"
        if [[ "${target}" == "frontend" ]]; then
          echo 'Skipping backend image build';
          exit 0;
        fi
        if [[ "${target}" != "backend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping backend image build for deploy target '${target}'";
          exit 0;
        fi
        docker build -t "${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/backend:${COMMIT_SHA}" .

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build frontend image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        target="${_DEPLOY_TARGET:-all}"
        if [[ "${target}" != "frontend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping frontend image build for deploy target '${target}'";
          exit 0;
        fi
        docker build -f frontend/Dockerfile -t "${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend:${COMMIT_SHA}" --build-arg "NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}" .

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push backend image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        target="${_DEPLOY_TARGET:-all}"
        if [[ "${target}" == "frontend" ]]; then
          echo 'Skipping backend image push';
          exit 0;
        fi
        if [[ "${target}" != "backend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping backend image push for deploy target '${target}'";
          exit 0;
        fi
        docker push "${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/backend:${COMMIT_SHA}"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push frontend image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        target="${_DEPLOY_TARGET:-all}"
        if [[ "${target}" != "frontend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping frontend image push for deploy target '${target}'";
          exit 0;
        fi
        docker push "${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend:${COMMIT_SHA}"

  - name: 'gcr.io/google-appengine/exec-wrapper'
    id: 'Run Prisma migrations'
    env:
      - 'CLOUD_SQL_PROXY_ARGS=--private-ip'
    args:
      - '-i'
      - 'node:20'
      - '-s'
      - '${_DB_CONNECTION_NAME}'
      - '-e'
      - 'DATABASE_URL'
      - '--'
      - 'bash'
      - '-lc'
      - |
          set -euo pipefail
          echo "[Run Prisma migrations] DEPLOY_TARGET=${_DEPLOY_TARGET}"

          if [[ "${_DEPLOY_TARGET}" != "backend" && "${_DEPLOY_TARGET}" != "all" && "${_DEPLOY_TARGET}" != "full" ]]; then
            echo "[Run Prisma migrations] Skipping migrations for DEPLOY_TARGET=${_DEPLOY_TARGET}"
            exit 0
          fi

          cd /workspace/backend
          echo "[Run Prisma migrations] Using schema prisma/schema.prisma"
          npx prisma migrate deploy --schema=prisma/schema.prisma
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy backend service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        target="${_DEPLOY_TARGET:-all}"
        if [[ "${target}" == "frontend" ]]; then
          echo 'Skipping backend deployment';
          exit 0;
        fi
        if [[ "${target}" != "backend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping backend deployment for deploy target '${target}'";
          exit 0;
        fi
        gcloud run deploy "hugs-backend-${_ENV}" \
          --image="${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/backend:${COMMIT_SHA}" \
          --region="${_GCP_REGION}" \
          --platform=managed \
          --quiet \
          --service-account="${_CLOUD_RUN_SA}" \
          --add-cloudsql-instances="${_DB_CONNECTION_NAME}" \
          --set-secrets="JWT_SECRET=jwt-secret:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest,POS_API_KEY=pos-api-key:latest,API_KEY=gemini-api-key:latest,DATABASE_URL=database-url:latest" \
          --allow-unauthenticated

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy frontend service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        target="${_DEPLOY_TARGET:-all}"
        if [[ "${target}" != "frontend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping frontend deployment for deploy target '${target}'";
          exit 0;
        fi
        gcloud run deploy "hugs-frontend-${_ENV}" \
          --image="${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend:${COMMIT_SHA}" \
          --region="${_GCP_REGION}" \
          --platform=managed \
          --quiet \
          --service-account="${_CLOUD_RUN_SA}" \
          --allow-unauthenticated \
          --set-env-vars="NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}"

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Smoke test services'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        target="${_DEPLOY_TARGET:-all}"
        if [[ "${target}" == "frontend" ]]; then
          echo 'Skipping smoke tests for backend services';
          exit 0;
        fi
        if [[ "${target}" != "backend" && "${target}" != "all" && "${target}" != "full" ]]; then
          echo "Skipping smoke tests for deploy target '${target}'";
          exit 0;
        fi
        set -euo pipefail
        BACKEND_URL_DEFAULT="${_BACKEND_URL}"
        if [[ -z "$${BACKEND_URL_DEFAULT}" ]]; then
          BACKEND_URL_DEFAULT=$$(gcloud run services describe "hugs-backend-${_ENV}" --platform managed --region ${_GCP_REGION} --format='value(status.url)')
        fi
        FRONTEND_URL=$$(gcloud run services describe "hugs-frontend-${_ENV}" --platform managed --region ${_GCP_REGION} --format='value(status.url)')
        BACKEND_URL="$$BACKEND_URL_DEFAULT" FRONTEND_URL="$$FRONTEND_URL" bash ci/check_post_deploy.sh

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: 'DATABASE_URL'

images:
  - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend:$COMMIT_SHA'
  - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend:$COMMIT_SHA'
